### PR TITLE
Update for hop-client 0.1, including writing a config.toml file for auth

### PR DESCRIPTION
**Pull request by myNameIsPatrick**
This PR makes update for hop-client 0.1, including:

* Write an additional TOML-based config file for hop-client. I opted for writing both rather than modifying the previous one so that kafkacat still works without any changes.
* Update what gets installed in the client container: hop-client 0.1.
* Minor changes to config writing to use a context handler.

I haven't verified that everything works as intended, but I wanted to run this by you first to see if this looks sensible.

### CODE REVIEW

**Comment by myNameIsPatrick** [comment]
Scratch looking at this for now, looks like I have a few things to fix on my end first.

**Comment by myNameIsPatrick** [comment]
Okay, so I'm not sure at this point what the issue with the tests are or if they should work in the CI pipeline.

**Comment by myNameIsPatrick** [comment]
> I actually don't know how Dockerfile.client builds. I checked out: origin/update/hop_0.1 and got an error when building:
> 
> ```
> ln: failed to create symbolic link '/root/.config/hop/config.toml': No such file or directory
> The command '/bin/sh -c ln -s /root/shared/config.toml ${HOME}/.config/hop/config.toml' returned a non-zero code: 1
> ```
> 
> I fixed it locally by explicitly creating the directory `/root/.config/hop`.
> 
> I think it is odd/misleading to use ${HOME} instead of /root, but it's just personal preference.

I wasn't too sure what to do here to be honest. I updated the client Dockerfile to remove that particular line before your reply but this may need to be changed. I'll try to give some context, and hopefully you have a solution that makes sense for this case.

So the way auth config is read in by the client has been changed, and it now expects a file (`config.toml`) to live either in `${HOME}/.config/hop` or if `XDG_CONFIG_PATH` is set, `${XDG_CONFIG_PATH}/hop`. So the question is, what's the right thing to do so that this works out? I'm unsure whether the config should be written to that path in the first place, or if XDG_CONFIG_PATH should be set to point at the right place (does this cause unexpected behavior?), or if some symlinking is preferred. 

> While the container builds, the tests don't pass. The container doesn't run successfully. The first error that I encountered running the container was `ModuleNotFoundError: No module named 'toml'`. So, the toml module needs to be installed in the container.

Oh right, that's my bad. I assumed that installing hop-client would have picked this up, but maybe the python 2 version is needed since that script assumes you're calling a python 2 interpreter? I can add in the relevant yum package...I think it's `python2-toml` but I would have to double-check.

> 
> Othewise, the changes look reasonable.

**Comment by rdt12** [comment]
> I actually don't know how Dockerfile.client builds. I checked out: origin/update/hop_0.1 and got an error when building:
> 
> ```
> ln: failed to create symbolic link '/root/.config/hop/config.toml': No such file or directory
> The command '/bin/sh -c ln -s /root/shared/config.toml ${HOME}/.config/hop/config.toml' returned a non-zero code: 1
> ```
> 
> I fixed it locally by explicitly creating the directory `/root/.config/hop`.
> 
> I think it is odd/misleading to use ${HOME} instead of /root, but it's just personal preference.
> 
> While the container builds, the tests don't pass. The container doesn't run successfully. The first error that I encountered running the container was `ModuleNotFoundError: No module named 'toml'`. So, the toml module needs to be installed in the container.
> 
> Othewise, the changes look reasonable.



> > I actually don't know how Dockerfile.client builds. I checked out: origin/update/hop_0.1 and got an error when building:
> > ```
> > ln: failed to create symbolic link '/root/.config/hop/config.toml': No such file or directory
> > The command '/bin/sh -c ln -s /root/shared/config.toml ${HOME}/.config/hop/config.toml' returned a non-zero code: 1
> > ```
> > 
> > 
> > I fixed it locally by explicitly creating the directory `/root/.config/hop`.
> > I think it is odd/misleading to use ${HOME} instead of /root, but it's just personal preference.
> 
> I wasn't too sure what to do here to be honest. I updated the client Dockerfile to remove that particular line before your reply but this may need to be changed. I'll try to give some context, and hopefully you have a solution that makes sense for this case.
> 
> So the way auth config is read in by the client has been changed, and it now expects a file (`config.toml`) to live either in `${HOME}/.config/hop` or if `XDG_CONFIG_PATH` is set, `${XDG_CONFIG_PATH}/hop`. So the question is, what's the right thing to do so that this works out? I'm unsure whether the config should be written to that path in the first place, or if XDG_CONFIG_PATH should be set to point at the right place (does this cause unexpected behavior?), or if some symlinking is preferred.

A symbolic link should work. It really doesn't matter whether ${HOME} is used or '/root' is used explicitly. I just think that ${HOME} looks odd. The important thing is that the directory where the symbolic link is created needs to exist.

This would be fine:
```
RUN mkdir -p /root/.config/hop && ln -s /root/shared/config.toml ${HOME}/.config/hop/config.toml
```
The reason for the symbolic links is to keep down the number of bind mounts. If everything that the client/server need is a symbolic link to something in one directory, `/root/shared`, then you just need one bind mount. If, instead, we wrote files to several different locations, you might need a bind mount for each file/directory in order to substitute your own persistent files.

> 
> > While the container builds, the tests don't pass. The container doesn't run successfully. The first error that I encountered running the container was `ModuleNotFoundError: No module named 'toml'`. So, the toml module needs to be installed in the container.
> 
> Oh right, that's my bad. I assumed that installing hop-client would have picked this up, but maybe the python 2 version is needed since that script assumes you're calling a python 2 interpreter? I can add in the relevant yum package...I think it's `python2-toml` but I would have to double-check.
> 
> > Othewise, the changes look reasonable.

The script is runServer.pl and it uses Python 3. The problem is that hop-client is not installed in Dockerfile.server, so toml is never installed. Explicitly installing toml in Dockerfile.server should work.

**Comment by myNameIsPatrick** [comment]
> A symbolic link should work. It really doesn't matter whether ${HOME} is used or '/root' is used explicitly. I just think that ${HOME} looks odd. The important thing is that the directory where the symbolic link is created needs to exist.
> 
> This would be fine:
> 
> ```
> RUN mkdir -p /root/.config/hop && ln -s /root/shared/config.toml ${HOME}/.config/hop/config.toml
> ```
> 
> The reason for the symbolic links is to keep down the number of bind mounts. If everything that the client/server need is a symbolic link to something in one directory, `/root/shared`, then you just need one bind mount. If, instead, we wrote files to several different locations, you might need a bind mount for each file/directory in order to substitute your own persistent files.

Thank for that explanation, that makes sense. I'll get that script to dump the auth config in /root/shared as well and try to avoid $HOME as the destination for the symlink if possible.

> The script is runServer and it uses Python 3. The problem is that hop-client is not installed in Dockerfile.server, so toml is never installed. Explicitly installing toml in Dockerfile.server should work.

Oh I see, I was playing around with the Dockerfile.client and not Dockerfile.server. I'll go and fix that.

**Comment by rdt12** [comment]
I encountered two issues. In runClientCommand in TestUtils.py you replaced an os.system call with a subprocess.Popen call. That was causing test_kafkaRunning to fail. I reverted. After I made that change, the hop command tests failed. I changed the environment variable from "XDG_CONFIG_PATH" to "XDG_CONFIG_HOME".

I also added a linear backoff in kafkaIsRunning. That didn't help kafkaIsRunning pass, but I left it in because it seems like it might help if it is taking a long time to bring up the server container.

I'll let you take a last look and then you can push if you'd like.

**Comment by myNameIsPatrick** [comment]
Thanks for catching and fixing those issues. I'll go ahead and merge this in.

**Pull request merged**
